int32 object_id
geometry_msgs/Pose object_pose
int32 num_configurations
---
srs_msgs/GraspConfiguration[] side
srs_msgs/GraspConfiguration[] mside
srs_msgs/GraspConfiguration[] front
srs_msgs/GraspConfiguration[] back
srs_msgs/GraspConfiguration[] top
srs_msgs/GraspConfiguration[] down
