(cl:defpackage srs_grasping-srv
  (:use )
  (:export
   "GETGRASPSFROMPOSITION"
   "<GETGRASPSFROMPOSITION-REQUEST>"
   "GETGRASPSFROMPOSITION-REQUEST"
   "<GETGRASPSFROMPOSITION-RESPONSE>"
   "GETGRASPSFROMPOSITION-RESPONSE"
   "GETGRASPCONFIGURATIONS"
   "<GETGRASPCONFIGURATIONS-REQUEST>"
   "GETGRASPCONFIGURATIONS-REQUEST"
   "<GETGRASPCONFIGURATIONS-RESPONSE>"
   "GETGRASPCONFIGURATIONS-RESPONSE"
  ))

