PREFIX srs: <http://www.srs-project.eu/ontologies/srs.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ipa-kitchen-map: <http://www.srs-project.eu/ontologies/ipa-kitchen-map.owl#>
SELECT ?x 
WHERE {"hhhh" srs:xCoordinate ?x .}
