
# KITCHEN__________________________________________________


# LIVING ROOM__________________________________________________


# BEDROOM______________________________________________________________

self_made_shelf:
  model: self_made_shelf
  model_type: urdf
  position: [-9.42, 11.48, 1.25]
  orientation: [0, 0, 1.570796327]

self_made_shelf_boundings_bottomPlate:
  model: self_made_shelf_boundings_bottomPlate
  model_type: urdf
  position: [-9.42, 11.48, 1.25]
  orientation: [0, 0, 1.570796327]

self_made_shelf_boundings_leftPlate:
  model: self_made_shelf_boundings_leftPlate
  model_type: urdf
  position: [-9.11, 11.48, 1.25]
  orientation: [0, 0, 1.570796327]

self_made_shelf_boundings_rightPlate:
  model: self_made_shelf_boundings_rightPlate
  model_type: urdf
  position: [-9.73, 11.48, 1.25]
  orientation: [0, 0, 1.570796327]

self_made_shelf_boundings_topPlate:
  model: self_made_shelf_boundings_topPlate
  model_type: urdf
  position: [-9.42, 11.48, 1.25]
  orientation: [0, 0, 1.570796327]

self_made_shelf_boundings_backPlate:
  model: self_made_shelf_boundings_backPlate
  model_type: urdf
  position: [-9.42, 11.48, 1.25]
  orientation: [0, 0, 1.570796327]

Bett_Fjellse:
  model: Bett_Fjellse
  model_type: urdf
  position: [-7.52, 11.84, 0.0]
  orientation: [0, 0, 0]

Nachttisch_Malm:
  model: Nachttisch_Malm
  model_type: urdf
  position: [-6.76, 12.53, 0.0]
  orientation: [0, 0, -1.570796327]

Lampe_Arstid:
  model: Lampe_Arstid
  model_type: urdf
  position: [-6.76, 12.53, 0.55]
  orientation: [0, 0, 0]

Kommode_Malm:
  model: Kommode_Malm
  model_type: urdf
  position: [-8.77, 13.64, 0.00]
  orientation: [0, 0, 3.141592654]

white_shelf2:
  model: white_shelf2
  model_type: urdf
  position: [-9.42, 11.54, 0]
  orientation: [0, 0, 1.570796327]

korbstuhl:
  model: korbstuhl
  model_type: urdf
  position: [-10.25, 13.24, 0.00]
  orientation: [0, 0, 0.45]

book_death:
  model: book_death
  model_type: urdf
# manipulation task position:
  position: [-9.34, 11.55, 1.4]
  orientation: [0, 0, 3.341592654]

book_romantiker:
  model: book_romantiker
  model_type: urdf
  position: [-9.688, 11.54, 1.4]
  orientation: [0, 0, 3.141592654]

book_gardening:
  model: book_gardening
  model_type: urdf
  position: [-9.627, 11.545, 1.4]
  orientation: [0, 0, 3.141592654]

book_heilkrauter:
  model: book_heilkrauter
  model_type: urdf
  position: [-9.483, 11.41, 1.3]
  orientation: [0, -1.570796, 3.141592654]

book_pferdewitze:
  model: book_pferdewitze
  model_type: urdf
  position: [-9.488, 11.405, 1.35]
  orientation: [0, -1.570796, 3.141592654]

medication_cetebe_empty:
  model: medication_cetebe_empty
  model_type: urdf
# search task position:
  position: [-8.47, 13.76, 0.811]
  orientation: [0, 0, 0]

wooden_box:
  model: wooden_box
  model_type: urdf
  position: [-8.7, 13.71, 0.852]
  orientation: [0, 0, -1.570796327]

swedish_pills:
  model: swedish_pills
  model_type: urdf
  position: [-8.44, 13.45, 0.78]
  orientation: [0, 0, -1.570796327]

black_vase_with_white_flower:
  model: black_vase_with_white_flower
  model_type: urdf
  position: [-8.64, 13.51, 0.78]
  orientation: [0, 0, 0]

book_very_large:
  model: book_very_large
  model_type: urdf
  position: [-9.03, 13.69, 0.81]
  orientation: [0, -1.570796, -1.570796327]

picture_frame:
  model: picture_frame
  model_type: urdf
  position: [-9.24, 11.47, 0.87]
  orientation: [0, 0, 1.570796327]

brown_basket:
  model: brown_basket
  model_type: urdf
  position: [-9.645, 11.45, 0.945]
  orientation: [0, 0, 0]

blanket_colored:
  model: blanket_colored
  model_type: urdf
  position: [-9.59, 11.62, 0.65]
  orientation: [0, 0, 1.570796327]

bedroom_picture:
  model: bedroom_picture
  model_type: urdf
  position: [-7.70, 11.31, 1.7]
  orientation: [0, 0, 0]

medication_prospan_empty:
  model: medication_prospan_empty
  model_type: urdf
  position: [-6.91, 12.66, 0.61]
  orientation: [0, 0, 0]

medication_mucoangin:
  model: medication_mucoangin
  model_type: urdf
# search task position:
  position: [-6.30, 13.73, 0.942]
  orientation: [0, 0, 3.541592654]

artificial_plant:
  model: artificial_plant
  model_type: urdf
  position: [-6.30, 12.10, 0.9]
  orientation: [0, 0, 3.141592654]

blanket_white:
  model: blanket_white
  model_type: urdf
  position: [-1.85, -1.31, 1.5]
  orientation: [0, 0, 0]

door_white_bedroom:
  model: door_white_bedroom
  model_type: urdf
  position: [-10.45, 11.535, 0]
  orientation: [0, 0, -1.570796327]

steckdosenleiste_schlafzimmer:
  model: steckdosenleiste_schlafzimmer
  model_type: urdf
  position: [-10.67, 13.75, 0.0]
  orientation: [0, 0, 0]

bedroom_rail:
  model: bedroom_rail
  model_type: urdf
  position: [-8.65, 13.78, 2.0]
  orientation: [0, 0, 0]


# FLOOR______________________________________________________________


blaueTuere01:
  model: blaueTuere01
  model_type: urdf
  position: [-5.68, -3.955, 0.00]
  orientation: [0, 0, 0]

blaueTuere02:
  model: blaueTuere02
  model_type: urdf
  position: [-11.80, 2.20, 0.00]
  orientation: [0, 0, 1.570796327]

polystyrene:
  model: polystyrene
  model_type: urdf
  position: [-9.07, 5.16, 0.00]
  orientation: [0, 0, 0]

boards_before_bedroom:
  model: boards_before_bedroom
  model_type: urdf
  position: [-12, 13.55, 0.25]
  orientation: [0, 0, 0]

locker_sliding_door1:
  model: locker_sliding_door1
  model_type: urdf
  position: [3.65, -5.545, 0]
  orientation: [0, 0, 1.570796327]

locker_sliding_door2:
  model: locker_sliding_door2
  model_type: urdf
  position: [0.05, -5.545, 0]
  orientation: [0, 0, 1.570796327]



