# insert an object instance into the ontology

# only object_id is used here at the moment. 
# it is attempted to automatically retrieve relevant information of this object, suppose the object has its 

#int32 object_id
srs_semantics_db/TBoxObject tbox_class
---
# if the object is inserted successfully
srs_semantics_db/ABoxObject[] list
