"""autogenerated by genmsg_py from IKGoal.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg
import std_msgs.msg

class IKGoal(roslib.message.Message):
  _md5sum = "be361c2f7296f2b7844f4d50c89e91ca"
  _type = "srs_grasping/IKGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
geometry_msgs/PoseStamped pre_pose
geometry_msgs/PoseStamped g_pose

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['pre_pose','g_pose']
  _slot_types = ['geometry_msgs/PoseStamped','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       pre_pose,g_pose
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(IKGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pre_pose is None:
        self.pre_pose = geometry_msgs.msg.PoseStamped()
      if self.g_pose is None:
        self.g_pose = geometry_msgs.msg.PoseStamped()
    else:
      self.pre_pose = geometry_msgs.msg.PoseStamped()
      self.g_pose = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.pre_pose.header.seq, _x.pre_pose.header.stamp.secs, _x.pre_pose.header.stamp.nsecs))
      _x = self.pre_pose.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.pre_pose.pose.position.x, _x.pre_pose.pose.position.y, _x.pre_pose.pose.position.z, _x.pre_pose.pose.orientation.x, _x.pre_pose.pose.orientation.y, _x.pre_pose.pose.orientation.z, _x.pre_pose.pose.orientation.w, _x.g_pose.header.seq, _x.g_pose.header.stamp.secs, _x.g_pose.header.stamp.nsecs))
      _x = self.g_pose.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.g_pose.pose.position.x, _x.g_pose.pose.position.y, _x.g_pose.pose.position.z, _x.g_pose.pose.orientation.x, _x.g_pose.pose.orientation.y, _x.g_pose.pose.orientation.z, _x.g_pose.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.pre_pose is None:
        self.pre_pose = geometry_msgs.msg.PoseStamped()
      if self.g_pose is None:
        self.g_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pre_pose.header.seq, _x.pre_pose.header.stamp.secs, _x.pre_pose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.pre_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pre_pose.pose.position.x, _x.pre_pose.pose.position.y, _x.pre_pose.pose.position.z, _x.pre_pose.pose.orientation.x, _x.pre_pose.pose.orientation.y, _x.pre_pose.pose.orientation.z, _x.pre_pose.pose.orientation.w, _x.g_pose.header.seq, _x.g_pose.header.stamp.secs, _x.g_pose.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.g_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.g_pose.pose.position.x, _x.g_pose.pose.position.y, _x.g_pose.pose.position.z, _x.g_pose.pose.orientation.x, _x.g_pose.pose.orientation.y, _x.g_pose.pose.orientation.z, _x.g_pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.pre_pose.header.seq, _x.pre_pose.header.stamp.secs, _x.pre_pose.header.stamp.nsecs))
      _x = self.pre_pose.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.pre_pose.pose.position.x, _x.pre_pose.pose.position.y, _x.pre_pose.pose.position.z, _x.pre_pose.pose.orientation.x, _x.pre_pose.pose.orientation.y, _x.pre_pose.pose.orientation.z, _x.pre_pose.pose.orientation.w, _x.g_pose.header.seq, _x.g_pose.header.stamp.secs, _x.g_pose.header.stamp.nsecs))
      _x = self.g_pose.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.g_pose.pose.position.x, _x.g_pose.pose.position.y, _x.g_pose.pose.position.z, _x.g_pose.pose.orientation.x, _x.g_pose.pose.orientation.y, _x.g_pose.pose.orientation.z, _x.g_pose.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.pre_pose is None:
        self.pre_pose = geometry_msgs.msg.PoseStamped()
      if self.g_pose is None:
        self.g_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pre_pose.header.seq, _x.pre_pose.header.stamp.secs, _x.pre_pose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.pre_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pre_pose.pose.position.x, _x.pre_pose.pose.position.y, _x.pre_pose.pose.position.z, _x.pre_pose.pose.orientation.x, _x.pre_pose.pose.orientation.y, _x.pre_pose.pose.orientation.z, _x.pre_pose.pose.orientation.w, _x.g_pose.header.seq, _x.g_pose.header.stamp.secs, _x.g_pose.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.g_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.g_pose.pose.position.x, _x.g_pose.pose.position.y, _x.g_pose.pose.position.z, _x.g_pose.pose.orientation.x, _x.g_pose.pose.orientation.y, _x.g_pose.pose.orientation.z, _x.g_pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
_struct_7d3I = struct.Struct("<7d3I")
