#get_objects_on_workspace
#object ID for the workspace
uint32 objectID
#Time stamp for the period
duration period # if empty then all the period
---
#list of objectID for possible objects on a given workspace
uint32[] objectID
#object class ID for each object on the workspace
uint32[] classID 