string map
# string location    # if null, then return all locations. Otherwise, specify the name of the location

---
#list 
# TODO: Better to wrap all parameters in one msg
string[] locations
geometry_msgs/Pose2D[] poses
string[] readableNames

string[] json_properties   # other properties in Json, such as Fridge inRoom Kitchen etc. 