#get_workspaces_on_map
#Time stamp for the period

string map

# flag: if need objectsInfo. False: objectsInfo will be empty. 
# when SRSFurnitureGeometry unavailable, corresponding items (e.g. x, y, z) will be set -1000 which is certainly invalid for srs. Or the whole will be set null
# default: true
bool ifGeometryInfo

---
#list of object ID for possible workspace in current map

string[] rooms
SRSSpatialInfo[] roomsInfo
