multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_footprint
    child_frame_id: base_footprint
groups:
  - name: arm
    base_link: base_link
    tip_link: sdh_palm_link

