/* Auto-generated by genmsg_cpp for file /home/emisario/git/care-o-bot/srs/srs_grasping/msg/GraspFResult.msg */
#ifndef SRS_GRASPING_MESSAGE_GRASPFRESULT_H
#define SRS_GRASPING_MESSAGE_GRASPFRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "srs_msgs/GraspSubConfiguration.h"

namespace srs_grasping
{
template <class ContainerAllocator>
struct GraspFResult_ {
  typedef GraspFResult_<ContainerAllocator> Type;

  GraspFResult_()
  : feasible_grasp_available(false)
  , grasp_configuration()
  {
  }

  GraspFResult_(const ContainerAllocator& _alloc)
  : feasible_grasp_available(false)
  , grasp_configuration(_alloc)
  {
  }

  typedef uint8_t _feasible_grasp_available_type;
  uint8_t feasible_grasp_available;

  typedef std::vector< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> >::other >  _grasp_configuration_type;
  std::vector< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> >::other >  grasp_configuration;


  ROS_DEPRECATED uint32_t get_grasp_configuration_size() const { return (uint32_t)grasp_configuration.size(); }
  ROS_DEPRECATED void set_grasp_configuration_size(uint32_t size) { grasp_configuration.resize((size_t)size); }
  ROS_DEPRECATED void get_grasp_configuration_vec(std::vector< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> >::other > & vec) const { vec = this->grasp_configuration; }
  ROS_DEPRECATED void set_grasp_configuration_vec(const std::vector< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> >::other > & vec) { this->grasp_configuration = vec; }
private:
  static const char* __s_getDataType_() { return "srs_grasping/GraspFResult"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "557fc92f838930c4c9fa17dc5fd74bbc"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool feasible_grasp_available\n\
srs_msgs/GraspSubConfiguration[] grasp_configuration\n\
\n\
================================================================================\n\
MSG: srs_msgs/GraspSubConfiguration\n\
float64[] sdh_joint_values\n\
geometry_msgs/Pose grasp\n\
geometry_msgs/Pose pre_grasp\n\
string category\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, feasible_grasp_available);
    ros::serialization::serialize(stream, grasp_configuration);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, feasible_grasp_available);
    ros::serialization::deserialize(stream, grasp_configuration);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(feasible_grasp_available);
    size += ros::serialization::serializationLength(grasp_configuration);
    return size;
  }

  typedef boost::shared_ptr< ::srs_grasping::GraspFResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srs_grasping::GraspFResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GraspFResult
typedef  ::srs_grasping::GraspFResult_<std::allocator<void> > GraspFResult;

typedef boost::shared_ptr< ::srs_grasping::GraspFResult> GraspFResultPtr;
typedef boost::shared_ptr< ::srs_grasping::GraspFResult const> GraspFResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::srs_grasping::GraspFResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::srs_grasping::GraspFResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace srs_grasping

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::srs_grasping::GraspFResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::srs_grasping::GraspFResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::srs_grasping::GraspFResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "557fc92f838930c4c9fa17dc5fd74bbc";
  }

  static const char* value(const  ::srs_grasping::GraspFResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x557fc92f838930c4ULL;
  static const uint64_t static_value2 = 0xc9fa17dc5fd74bbcULL;
};

template<class ContainerAllocator>
struct DataType< ::srs_grasping::GraspFResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "srs_grasping/GraspFResult";
  }

  static const char* value(const  ::srs_grasping::GraspFResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::srs_grasping::GraspFResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool feasible_grasp_available\n\
srs_msgs/GraspSubConfiguration[] grasp_configuration\n\
\n\
================================================================================\n\
MSG: srs_msgs/GraspSubConfiguration\n\
float64[] sdh_joint_values\n\
geometry_msgs/Pose grasp\n\
geometry_msgs/Pose pre_grasp\n\
string category\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::srs_grasping::GraspFResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::srs_grasping::GraspFResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.feasible_grasp_available);
    stream.next(m.grasp_configuration);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GraspFResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srs_grasping::GraspFResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::srs_grasping::GraspFResult_<ContainerAllocator> & v) 
  {
    s << indent << "feasible_grasp_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feasible_grasp_available);
    s << indent << "grasp_configuration[]" << std::endl;
    for (size_t i = 0; i < v.grasp_configuration.size(); ++i)
    {
      s << indent << "  grasp_configuration[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::srs_msgs::GraspSubConfiguration_<ContainerAllocator> >::stream(s, indent + "    ", v.grasp_configuration[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // SRS_GRASPING_MESSAGE_GRASPFRESULT_H

