; Auto-generated. Do not edit!


(cl:in-package srs_grasping-msg)


;//! \htmlinclude GraspFFeedback.msg.html

(cl:defclass <GraspFFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GraspFFeedback (<GraspFFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspFFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspFFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name srs_grasping-msg:<GraspFFeedback> is deprecated: use srs_grasping-msg:GraspFFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspFFeedback>) ostream)
  "Serializes a message object of type '<GraspFFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspFFeedback>) istream)
  "Deserializes a message object of type '<GraspFFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspFFeedback>)))
  "Returns string type for a message object of type '<GraspFFeedback>"
  "srs_grasping/GraspFFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspFFeedback)))
  "Returns string type for a message object of type 'GraspFFeedback"
  "srs_grasping/GraspFFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspFFeedback>)))
  "Returns md5sum for a message object of type '<GraspFFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspFFeedback)))
  "Returns md5sum for a message object of type 'GraspFFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspFFeedback>)))
  "Returns full string definition for message of type '<GraspFFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspFFeedback)))
  "Returns full string definition for message of type 'GraspFFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspFFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspFFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspFFeedback
))
