; Auto-generated. Do not edit!


(cl:in-package srs_grasping-msg)


;//! \htmlinclude GraspCFeedback.msg.html

(cl:defclass <GraspCFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GraspCFeedback (<GraspCFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspCFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspCFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name srs_grasping-msg:<GraspCFeedback> is deprecated: use srs_grasping-msg:GraspCFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspCFeedback>) ostream)
  "Serializes a message object of type '<GraspCFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspCFeedback>) istream)
  "Deserializes a message object of type '<GraspCFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspCFeedback>)))
  "Returns string type for a message object of type '<GraspCFeedback>"
  "srs_grasping/GraspCFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspCFeedback)))
  "Returns string type for a message object of type 'GraspCFeedback"
  "srs_grasping/GraspCFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspCFeedback>)))
  "Returns md5sum for a message object of type '<GraspCFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspCFeedback)))
  "Returns md5sum for a message object of type 'GraspCFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspCFeedback>)))
  "Returns full string definition for message of type '<GraspCFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspCFeedback)))
  "Returns full string definition for message of type 'GraspCFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspCFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspCFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspCFeedback
))
