; Auto-generated. Do not edit!


(cl:in-package srs_grasping-msg)


;//! \htmlinclude GraspFGoal.msg.html

(cl:defclass <GraspFGoal> (roslisp-msg-protocol:ros-message)
  ((object_id
    :reader object_id
    :initarg :object_id
    :type cl:integer
    :initform 0)
   (object_pose
    :reader object_pose
    :initarg :object_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass GraspFGoal (<GraspFGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspFGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspFGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name srs_grasping-msg:<GraspFGoal> is deprecated: use srs_grasping-msg:GraspFGoal instead.")))

(cl:ensure-generic-function 'object_id-val :lambda-list '(m))
(cl:defmethod object_id-val ((m <GraspFGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader srs_grasping-msg:object_id-val is deprecated.  Use srs_grasping-msg:object_id instead.")
  (object_id m))

(cl:ensure-generic-function 'object_pose-val :lambda-list '(m))
(cl:defmethod object_pose-val ((m <GraspFGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader srs_grasping-msg:object_pose-val is deprecated.  Use srs_grasping-msg:object_pose instead.")
  (object_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspFGoal>) ostream)
  "Serializes a message object of type '<GraspFGoal>"
  (cl:let* ((signed (cl:slot-value msg 'object_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspFGoal>) istream)
  "Deserializes a message object of type '<GraspFGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'object_id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspFGoal>)))
  "Returns string type for a message object of type '<GraspFGoal>"
  "srs_grasping/GraspFGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspFGoal)))
  "Returns string type for a message object of type 'GraspFGoal"
  "srs_grasping/GraspFGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspFGoal>)))
  "Returns md5sum for a message object of type '<GraspFGoal>"
  "cb5903652a339bd327b00b1b46412c31")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspFGoal)))
  "Returns md5sum for a message object of type 'GraspFGoal"
  "cb5903652a339bd327b00b1b46412c31")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspFGoal>)))
  "Returns full string definition for message of type '<GraspFGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 object_id~%geometry_msgs/Pose object_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspFGoal)))
  "Returns full string definition for message of type 'GraspFGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 object_id~%geometry_msgs/Pose object_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspFGoal>))
  (cl:+ 0
     4
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspFGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspFGoal
    (cl:cons ':object_id (object_id msg))
    (cl:cons ':object_pose (object_pose msg))
))
