; Auto-generated. Do not edit!


(cl:in-package srs_grasping-msg)


;//! \htmlinclude GraspFeedback.msg.html

(cl:defclass <GraspFeedback> (roslisp-msg-protocol:ros-message)
  ((fb
    :reader fb
    :initarg :fb
    :type cl:string
    :initform ""))
)

(cl:defclass GraspFeedback (<GraspFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name srs_grasping-msg:<GraspFeedback> is deprecated: use srs_grasping-msg:GraspFeedback instead.")))

(cl:ensure-generic-function 'fb-val :lambda-list '(m))
(cl:defmethod fb-val ((m <GraspFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader srs_grasping-msg:fb-val is deprecated.  Use srs_grasping-msg:fb instead.")
  (fb m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspFeedback>) ostream)
  "Serializes a message object of type '<GraspFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'fb))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'fb))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspFeedback>) istream)
  "Deserializes a message object of type '<GraspFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'fb) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'fb) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspFeedback>)))
  "Returns string type for a message object of type '<GraspFeedback>"
  "srs_grasping/GraspFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspFeedback)))
  "Returns string type for a message object of type 'GraspFeedback"
  "srs_grasping/GraspFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspFeedback>)))
  "Returns md5sum for a message object of type '<GraspFeedback>"
  "68883bc8fcde149fd89e9e137bc4e92b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspFeedback)))
  "Returns md5sum for a message object of type 'GraspFeedback"
  "68883bc8fcde149fd89e9e137bc4e92b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspFeedback>)))
  "Returns full string definition for message of type '<GraspFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string fb~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspFeedback)))
  "Returns full string definition for message of type 'GraspFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string fb~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'fb))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspFeedback
    (cl:cons ':fb (fb msg))
))
