include $(shell rospack find mk)/cmake.mk

#all: downloadjar

#TARBALL = lib/javaGeom-0.10.2.jar
#TARBALL_URL = http://sourceforge.net/projects/geom-java/files/javaGeom/javaGeom%200.10.2/javaGeom-0.10.2.jar/download
#downloadjar: 
# 	ifeq ($(findstring $(TARBALL))
# 		echo 'file exists'
# 	else
#	echo 'start download\n'
#	`rospack find rosbuild`/bin/download_checkmd5.py $(TARBALL_URL) $(TARBALL)
#	echo 'stop download\n'
# 	endif
#clean:
#	-rm -rf $(TARBALL)
#wipe: clean
#	-rm -rf build
