################
# continuous recording
continuous_topics: [/tf, /joint_states, /base_controller/command_safe, /base_controller/command, /spacenav/offset, /spacenav/rot_offset, /spacenav/joy]

################
# triggered recording
trigger_topics: [/cam3d_throttled/rgb/image_color, /map] #ADD interactive marker for arm, bb position, bb size, arm navigation state, 

# setup time trigger
trigger_timestep: 10

# setup tf triggers
trigger_record_translation: 0.5
trigger_record_rotation: 0.1
wanted_tfs:
 - reference_frame: /map
   target_frame: /base_link
   trigger_record_translation: 0.5
   trigger_record_rotation: 0.1
 - reference_frame: /base_link
   target_frame: /arm_7_link
   trigger_record_translation: 0.1
   trigger_record_rotation: 0.1
