
# KITCHEN__________________________________________________

table_ikea:
  model: table_ikea
  model_type: urdf.xacro
# normal position
  position: [2.55,-0.685, 0]
  orientation: [0, 0, 1.570796]
# narrow passage position
#  position: [1.53,-0.495, 0]
#  orientation: [0, 0, 1.570796]

table_ikea_bjursta:
  model: table_ikea_bjursta
  model_type: urdf
# normal position
  position: [2.54,-0.66, 0]
  orientation: [0, 0, 1.570796]

table_ikea_bjursta_narrow_passage:
  model: table_ikea_bjursta_narrow_passage
  model_type: urdf
# narrow passage position
  position: [1.52,-0.47, 0]
  orientation: [0, 0, 1.570796]

Stuhl_borje:
  model: Stuhl_borje
  model_type: urdf
# normal position
  position: [2.55, -0.05, 0.00]
  orientation: [0, 0, 0]
# narrow passage position
  #position: [0.9, -0.5, 0.00]
  #orientation: [0, 0, 1.570796]

Stuhl_borje2:
  model: Stuhl_borje2
  model_type: urdf
# normal position
  position: [2.55, -1.30, 0.00]
  orientation: [0, 0, 3.141592654]
# narrow passage position
  #position: [1.55, -1.15, 0.00]
  #orientation: [0, 0, 3.141592654]

apple_juice_box:
  model: apple_juice_box
  model_type: urdf
# manipulation task position
  position: [2.22, -0.70, 0.9]
  orientation: [0, 0.50, 1.3]

orange_juice:
  model: orange_juice
  model_type: urdf
# normal position
  position: [2.31, -0.54, 0.8]
  orientation: [0, 1.570796, 0]
# narrow passage position
  #position: [1.29, -0.35, 0.8]
  #orientation: [0, 1.570796, 0]

orange_juice2:
  model: orange_juice2
  model_type: urdf
# normal position
  position: [2.31, -0.54, 0.9]
  orientation: [0, 1.570796, -0.3]
# narrow passage position
  #position: [1.29, -0.35, 0.9]
  #orientation: [0, 1.570796, -0.3]

green_tea:
  model: green_tea
  model_type: urdf
# normal position
  position: [2.55, -0.8, 0.8]
  orientation: [0, 1.570796, 0.9]
# narrow passage position
#  position: [1.53, -0.61, 0.8]
#  orientation: [0, 1.570796, 0.9]

green_tea2:
  model: green_tea2
  model_type: urdf
# manipulation task position
  position: [2.48, -0.7, 0.83]
  orientation: [0, 1.15, -0.6]

zwieback_alternative:
  model: zwieback_alternative
  model_type: urdf
# normal position
  position: [2.52, -0.58, 0.85]
  orientation: [0, 0, 0.6]
# narrow passage position
  #position: [1.50, -0.39, 0.85]
  #orientation: [0, 0, 0.6]

basmati_rice:
  model: basmati_rice
  model_type: urdf
# normal position
  position: [2.8, -0.95, 0.8]
  orientation: [0, -1.570796, 3.5]
# narrow passage position
  #position: [1.78, -0.76, 0.8]
  #orientation: [0, -1.570796, 3.5]

kitekat:
  model: kitekat
  model_type: urdf
  position: [-1.85, -0.3, 0.99]
  orientation: [0, 0, 3.141592654]

corn_flakes_package:
  model: corn_flakes_package
  model_type: urdf
  position: [-1.55, -0.51, 1.03]
  orientation: [0, 0, 0.4]

spaghetti:
  model: spaghetti
  model_type: urdf
  position: [-1.85, 0.61, 1.475]
  orientation: [0, 0, 0]

plastic_wrap:
  model: plastic_wrap
  model_type: urdf
  position: [-1.85, -1.31, 1.46]
  orientation: [0, 0, 0]

flower_in_pot1:
  model: flower_in_pot1
  model_type: urdf
  position: [-1.85, -0.61, 1.44]
  orientation: [0, 0, 0]

flower_in_pot2:
  model: flower_in_pot2
  model_type: urdf
  position: [1, 1.85, 0.9]
  orientation: [0, 0, 0]

kitchen_plank:
  model: kitchen_plank
  model_type: urdf
  position: [-1.85, -0.536, 1.40]
  orientation: [0, 0, 0]


crate_small:
  model: crate_small
  model_type: urdf
# narrow passage position
  position: [1.76, -2.15, 0.35]
  orientation: [0, 0, -0.9]

crate_small2:
  model: crate_small2
  model_type: urdf
# narrow passage position
  position: [1.74, -1.63, 0.35]
  orientation: [0, 0, -0.9]

crate_small3:
  model: crate_small3
  model_type: urdf
# narrow passage position
  position: [2.9, 0.6, 0.35]
  orientation: [0, 0, -0.9]

crate_large:
  model: crate_large
  model_type: urdf
# narrow passage position
  position: [1.8, -2.19, 0.00]
  orientation: [0, 0, 0]

crate_large2:
  model: crate_large2
  model_type: urdf
# narrow passage position
  position: [1.8, -1.69, 0.00]
  orientation: [0, 0, 0]

crate_large3:
  model: crate_large3
  model_type: urdf
# narrow passage position
  position: [2.97, 0.52, 0.00]
  orientation: [0, 0, -1.570796327]

SRS_divider1:
  model: SRS_divider1
  model_type: urdf
  position: [-0.52, -2.58, 0.00]
  orientation: [0, 0, 1.570796327]

SRS_divider2:
  model: SRS_divider2
  model_type: urdf
  position: [2.49, -2.59, 0.00]
  orientation: [0, 0, 1.570796327]

SRS_divider3:
  model: SRS_divider3
  model_type: urdf
  position: [3.46, -0.44, 0.00]
  orientation: [0, 0, 1.570796327]

SRS_divider4:
  model: SRS_divider4
  model_type: urdf
  position: [-2.03, -2.308, 0.00]
  orientation: [0, 0, 0]

SRS_divider5:
  model: SRS_divider5
  model_type: urdf
  position: [3.95, -2.59, 0.00]
  orientation: [0, 0, 1.570796327]

SRS_divider6:
  model: SRS_divider6
  model_type: urdf
  position: [5.01, -2.59, 0.00]
  orientation: [0, 0, 1.570796327]

SRS_divider7:
  model: SRS_divider7
  model_type: urdf
  position: [5.76, -2.54, 0.00]
  orientation: [0, 0, 1.570796327]

schrank_diamondback:
  model: schrank_diamondback
  model_type: urdf
  position: [-0.6, 1.47, 0.00]
  orientation: [0, 0, -1.570796327]

kitchen_big_cabinet:
  model: kitchen_big_cabinet
  model_type: urdf
  position: [1.30, 1.46, 0.00]
  orientation: [0, 0, 0]

tea_box:
  model: tea_box
  model_type: urdf
  position: [-1.85, -1.31, 1.5]
  orientation: [0, 0, 0]

salt_alternative:
  model: salt_alternative
  model_type: urdf
  position: [-1.85, -1.31, 1.5]
  orientation: [0, 0, 0]


# LIVING ROOM__________________________________________________

# BEDROOM______________________________________________________________

# FLOOR______________________________________________________________


locker_sliding_door1:
  model: locker_sliding_door1
  model_type: urdf
  position: [3.65, -5.545, 0]
  orientation: [0, 0, 1.570796327]

locker_sliding_door2:
  model: locker_sliding_door2
  model_type: urdf
  position: [0.05, -5.545, 0]
  orientation: [0, 0, 1.570796327]


# OTHER OBJECTS______________________________________________________


# IPA OBJECTS_________________________________________________________

