# Action server is implemented in RVIZ plugin which acts as bb_estimator client
# goal
string object_name
bool disable_video # aka useless mode for RVIZ plugin
---
# result
int16[2] p1
int16[2] p2
#string im_primitive_name
---
# feedback
time timestamp
int16[2] p1
int16[2] p2
