# goal
string action # description what to do
bool allow_repeat
string object_name
---
# result
bool success
bool failed
bool repeat
bool timeout
bool collision
duration time_elapsed
---
# feedback
bool starting
bool planning
bool executing
bool reset